### ISSUE TITLE
Implement AllocatedScalar for PLONKup back end prover

### ISSUE THREAD

**Issue by Bounce23** [dusk-network/plonk#569] opened 2021-09-14 14:35 UTC
The backend of PLONKup uses Variables as gate inputs. As a result the inner represented scalar cannot be accessed outside of this lib. This must be changed to AllocatedScalar so we can use particular hash gadgets.

**Comment by CPerezz** [comment] 2021-09-15 07:53
Duplicate of #565

**Closed by CPerezz** 2021-09-15 07:53 UTC
